<?php include('include/header.php'); ?>

<div class="container" style="box-shadow: 2px 2px 20px #ccc;margin-top: 25px;">
	<h1 style="text-align: center;">Terms And Conditions</h1>
	<p style="font-size: 12px;">The website Klitestays.com is published and maintained by Buddies e-com solutions Private Limited Company, a company incorporated and existing in accordance with the laws of India When you access, browse or use this site, you accept, without limitation or qualification, the terms and conditions set forth herein. When you access any of the sub- sites (whether belonging to an 'associate' of Company or otherwise) through this site, then such sub- site may have its own terms and conditions, which are specific to such sub- site.
These Terms and Conditions of use and any additional terms posted on this site together constitute the entire agreement between Company and you with respect to your use of this Site.
</p>
<p style="font-size: 14px;">Contents Of The Site :</p>
<ul style="font-size: 12px;">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>This Site is only for your personal use. You shall not distribute exchange, modify, sell or transmit anything you copy from this Site, including but not limited to any text, images, audio and video, for any business, commercial or public purpose</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>As long as you comply with the terms of these Terms and Conditions of Use, Company grants you a non-exclusive, non-transferable, limited right to enter, view and use this Site. You agree not to interrupt or attempt to interrupt the operation of this Site in any manner whatsoever.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Access to certain areas of the Site may only be available to registered members. To become a registered member, you may be required to answer certain questions or provide certain details. Answers to such questions or details required may be mandatory and/or optional. You represent and warrant that all information you supply to us, about yourself, and others, is true and accurate.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>You are requested to report to content info@klitestays.com in the event you find any content on the Website which you deem is unlawful, libelous, defamatory, obscene, pornographic, indecent, lewd, suggestive, harassing, threatening, invasive of privacy or publicity rights, abusive, inflammatory, fraudulent or otherwise objectionable, against any religious beliefs, spam, potentially infringing or is not authorized by the intellectual property rights owner or is transgression of any applicable law. On receiving such report, the Company reserves the right to investigate and/or take such action as the Company may deem appropriate.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>For privacy policy, please visit […]</li>
</ul>
<p style="font-size: 14px;">Ownership :</p>
<ul style="font-size: 12px">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>All materials on this Site, including but not limited to audio, images, software, text, icons and such like (the "Content"), are protected by copyright under international conventions and copyright laws. You cannot use the Content for any purpose, except as specified herein.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>You agree to follow all instructions so provided on this Site limiting the way you may use the Content.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Any unauthorized use of the Content may violate copyright laws, trademark laws, the laws of privacy and publicity, and civil and criminal statutes.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>You may download such copy/copies of the Content to be used only by you for your personal use.</li>
</ul>
<p style="font-size: 14px;">Company Rights :</p>
<ul style="font-size: 12px">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>If you send any communications or materials to the Site by electronic mail or otherwise, including any comments, data, questions, suggestions or the like, all such communications are, and will be treated by Company, as non-confidential.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>You hereby give up any and all claim that any use of such material violates any of your rights including moral rights, privacy rights, proprietary or other property rights, publicity rights, rights to credit for material or ideas, or any other right, including the right to approve the way the Company uses such material.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Any material submitted to this Site may be adapted, broadcast, changed, copied, disclosed, licensed, performed, posted, published, sold, transmitted or used by Company anywhere in the world, in any medium, forever.</li>
</ul>
<p style="font-size: 14px;">Transmitted Material :</p>
<ul style="font-size: 12px;">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Internet transmissions are never completely private or secure. You understand that any message or information you send to this Site may be read or intercepted by others unless there is a special notice that a particular message (for example, credit card/debit card/bank information) is encrypted (send in code). Sending a message to Company does not cause Company to have any special responsibility to you.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The copyright in the contents of this Site belongs to Company. Accordingly, Company reserves all rights. Copying of part or all the contents of this Site without permission of Company is prohibited except to the extent that such copying/printing is necessary for the purposes of availing of the services.</li>
</ul>
<p style="font-size: 14px">Disclaimer :</p>
<ul style="font-size: 12px;">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The material in this Site could include technical inaccuracies or typographical errors. Company may make changes/modifications or improvements on the Site at any time.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The materials on this Site are provided on an "As Is" basis, without warranties of any kind either expressed or implied. To the fullest extent permissible pursuant to applicable law, Company disclaims all warranties of merchantability and fitness for a particular purpose.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Company does not warrant that the functions contained in this Site will be uninterrupted or error free, that defects will be corrected, or that this Site or the servers that make it available are free of viruses or other harmful components, but shall endeavor to ensure your fullest satisfaction. Company does not warrant or make any representations regarding the use of or the result of the use of the material on the Site in terms of their correctness, accuracy, reliability, or otherwise, insofar as such material is derived from other service providers such as airlines, hotel owners and tour operators.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>You acknowledge that this Site is provided only on the basis set out in these terms and conditions. Your uninterrupted access or use of this Site on this basis may be prevented by certain factors outside our reasonable control including, without limitation, the unavailability, inoperability or interruption of the Internet or other telecommunications services or as a result of any maintenance or other service work carried out on this Website. Company does not accept any responsibility and will not be liable for any loss or damage whatsoever arising out of or in connection with any ability/inability to access or to use the Site.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>You also acknowledge that through this Site, Company merely provides intermediary services in order to facilitate booking of tickets and hotel services to you. Company is not the last-mile service provider to you and therefore, Company shall not be or deemed to be responsible for any lack or deficiency of services provided by any person (airline, travel/tour operator, hotel, facility or similar agency) you shall engage or hire or appoint pursuant to or resulting from, the material available in this Site.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Company will not be liable to you or to any other person for any direct, indirect, incidental, punitive or consequential loss, damage, cost or expense of any kind whatsoever and howsoever caused from out of your usage of this Site.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>If for any reason, law does not permit exclusions of liability then, the liability of the Company shall be limited to such amount paid by the user and retained by the Company for the transaction in question.</li>
</ul>
<p style="font-size: 14px;">General Provisions :</p>
<ul style="font-size: 12px;">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Company may add to, modify or remove any part of these Terms and Conditions of Use at any time as it may deem fit, without notice. Any changes to these Terms and Conditions of Use or any terms posted on this Site apply as soon as they are posted. By continuing to use this Site after any changes are posted, you are indicating your acceptance of those changes.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Company may add, change, discontinue, remove or suspend any other Content posted on this Site, including features and specifications of products described or depicted on the Site, temporarily or permanently, at any time, without notice and without liability.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Company reserves the right to undertake all necessary steps to ensure that the security, safety and integrity of Company's systems as well as its clients and users interests are and remain, well-protected. Towards this end, Company may take various steps to verify and confirm the authenticity, enforceability and validity of orders placed by you.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>By offering for sale travel to particular destinations, Company does not represent or warrant that travel to such point is advisable or without risk. Company does not accept liability for damages, losses, or delays that may result from improper documents for entry, exit, length of stay, or from travel to such destinations.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Company reserves its exclusive right in its sole discretion to alter, limit or discontinue the Site or any material posted herein, in any respect. Company shall have no obligation to take the needs of any User into consideration in connection therewith.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Company reserves its right to deny in its sole discretion any user access to this Site or any portion hereof without notice.
    </li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>No waiver by Company of any provision of these Terms and Conditions shall be binding except as set forth in writing and signed by its duly authorized representative.</li>
</ul>
<p style="font-size: 14px;">Disputes :</p>
<ul style="font-size: 12px;">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>If any dispute arises between you and Company during your use of the Site or thereafter, in connection with and arising from your use or attempt to use this Site, the dispute shall be referred to arbitration. Both parties shall agree to a sole arbitrator. The place of arbitration shall be Pondicherry. The arbitration proceedings shall be in the English language.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The said arbitration proceedings shall be governed and construed in accordance with the Arbitration and Conciliation Act, 1996 and modifications thereof as in force at the relevant time.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>These terms and conditions are governed by and shall be construed in accordance with the laws of the Republic of India and any dispute shall exclusively be subject to the jurisdiction of the appropriate Courts situated at Pondicherry, India.</li>
</ul>
<p style="font-size: 14px;">Hotel Terms And Conditions :</p>
<p style="font-size: 13px;">Apart from the general terms and conditions, the below mentioned are the specific hotel terms.</p>
<ul style="font-size: 12px;">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Klitestays.com acts only as an intermediary agent with only the role of a mediator. Even if you make a booking through us, the contract will be between the supplier and you and the general travel and contractual terms and conditions of the supplier shall apply. We are not a party to the contractual relationship.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Hotels may not allow local residents to check-in as guests. This is strictly subject to the Hotel Policies and klitestays.com will not be responsible for such check-in denials.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Hotels reserve the right of admission. Unmarried/unrelated couples may not be allowed to check-in. Similarly accommodation can be denied to guests posing as a Couple if suitable proof of identification is not presented at check-in. Klitestays.com will not be responsible for any check-in denied by the hotel due to the aforesaid reason. No refund would be applicable in case the hotel denies check-in under such circumstances.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Hotel may deny check in to guests providing Id Proof of the same city as the hotel itself.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The hotel pictures/information on the website, including amenities and facilities are provided by the hotel. This information is for reference only. For any discrepancy that exists between the website pictures and actual settings, Klitestays.com is not liable and responsible.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>It is mandatory for you to send the auto generated form filling your correct credit card details immediately to the hotel in order for the booking to be confirmed by the hotel/accommodation.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The booking is not confirmed until the filled auto generated form is sent to the hotel.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The credit card details should be sent only via the auto generated form and in no other format.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Prior to the filling of the auto generated form being sent to the hotel by you, your booking is only provisional and hotel has no obligation to reserve a room for you.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The hotel shall confirm your booking post authorizing and verifying the credit card details.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The hotel may deny your booking if it is not able to authenticate and verify the credit card details as per its terms and conditions.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The Company does not store your credit card in details database as they are sent by you directly to the hotel and stored by the hotel.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The hotel might block your credit card for the amount of the booking as per the hotel's terms and conditions and the Company shall not be responsible for the same.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The primary guest must be at least 18 years old to be able to check into the hotel.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Check-in time and check-out time is as per hotel policy & terms. Early check-in or late check-out request is subject to availability and the hotel might charge you extra for it. Please note that the check-in time is subject to change as per hotel policy & seasonality.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Your stay does not include additional personal expenses like telephone charges, meals that aren't part of your meal plan, any hotel services you use (like laundry and room service) or tips. The hotel will charge you directly for these when you're checking out.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>It is mandatory for guests to present valid photo identification at the time of check-in. According to government regulations, a valid Photo ID has to be carried by every person above the age of 18 staying at the hotel. The identification proofs accepted are Drivers License, Voters Card, and Passport. Without valid ID the guest will not be allowed to check in. Note- PAN Cards will not be accepted as a valid ID card.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>The hotel reserves the right of admission. Accommodation can be denied to guests posing as a 'couple' if suitable proof of identification is not presented at check-in. Company will not be responsible for any check-in denied by the hotel due to the aforesaid reason.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Hotels may charge a mandatory meal surcharge on festive periods e.g. Christmas/ New Year's Eve or other festivals as decided by the hotel. All additional charges (including mandatory meal surcharges) need to be cleared directly at the hotel.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Time Zone applicable for content displayed on the website shall be Indian Standard Time for all purposes unless explicitly mentioned otherwise.</li>
</ul>
<p style="font-size: 14px;">Additional Terms And Conditions Applicable Ror All Hotel Offers :</p>
<p style="font-size: 13px;">Klitestays.com reserves the right to:</p>
<ul style="font-size: 12px;">
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>discontinue or extend the Cash back period without assigning any reasons whatsoever;</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Change/ amend / add /delete/ modify terms and conditions of this Cash back without assigning any reasons whatsoever. Customers acknowledge that they will not be personally advised of any such change/ amendment / addition /deletion/ modification. Customers are advised to check for any such change/ amendment / addition /deletion/ modification regularly. Customers hereby unconditionally agree to all such changes/ amendments/ additions/ deletions/ modifications.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>All taxes, duties, levies or other statutory dues and charges payable in connection with the benefits accruing under the Cash back shall be borne solely by the Customer and Klitestays.com shall not be liable in any manner whatsoever for any such taxes, duties, levies or other statutory dues and charges.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Customers are requested to be accustomed, satisfy and agree to with these terms and conditions of the Cash back before participating in or making any purchase in relation to this Cash back. Participation in the Cash back is discretion of Customer.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Customers are not being charged extra for participating in the Cash back.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Liability of Klitestays.com shall be limited to the extent of the cash back to which Customer is entitled as per terms and conditions.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>Decision of Klitestays.com in respect of Cash back, benefits or any matters related thereto shall be final and binding and no correspondence will be entertained in this behalf.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>All disputes are subject to exclusive jurisdiction of the competent courts in Pondicherry only.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>By participating in this Scheme, Customers agree to be bound by these terms and conditions and waive any right to claim ambiguity in these terms & conditions. Klitestays.com does not provide any warranties with regard to the quality or fitness for any purpose of the hotels available under the Cash back. Customers agree to release, discharge, indemnify and hold harmless Klitestays.com, and its directors, officers, employees and agents, from and against any claims, damages or liability due to any injuries or losses to any person (including death) or property of any kind resulting in whole or in part, directly or indirectly, from acceptance, use, or loss of any Cash back related benefit/hotel booking, or participation in any Cash back-related activity or participation herein.</li>
	<li><i class="material-icons" style="font-size: 12px;position: relative;left: -5px;">send</i>All other standard terms and conditions applicable are listed on […]</li>
	
</ul>
</div>
<?php include('include/footer.php'); ?>